### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by FeiNiao** [1c3z/ARL-NPoC#14]
语法：xing scan -t .\url.txt --plugin-name U8
![image](https://github.com/1c3z/ARL-NPoC/assets/66779835/b8d811f6-f9f0-4be2-b537-b542caa9e65f)

![image](https://github.com/1c3z/ARL-NPoC/assets/66779835/31413481-e8a1-442a-bbfd-ee72499dc908)

**Comment by 1c3z** [comment]
试了下没发现问题。

![image](https://github.com/1c3z/ARL-NPoC/assets/9052484/f6936fa3-e8db-4966-bb5e-82298a19ba62)

xing list 有数据么？ 



![image](https://github.com/1c3z/ARL-NPoC/assets/9052484/f9059a80-035e-4c41-9a06-3428cb49d335)

**Comment by FeiNiao** [comment]
我换了Linux环境也还是不行的
![image](https://github.com/1c3z/ARL-NPoC/assets/66779835/cdcc7b30-30e2-4812-a72c-8ad2f232b7d3)

我还以为是系统的问题，但是我换了Linux还是不行，xing list无数据

**Comment by 1c3z** [comment]
这里安装了两次。第一个要删了。

![image](https://github.com/1c3z/ARL-NPoC/assets/9052484/be647908-e37d-4573-92b8-bb99ef57fe36)

**Comment by FeiNiao** [comment]
我把第一个的文件删除了，但是执行后报错了

![image](https://github.com/1c3z/ARL-NPoC/assets/66779835/68eff2ad-1f26-4bab-9700-9b54bc082120)

![image](https://github.com/1c3z/ARL-NPoC/assets/66779835/9972b213-aa71-447b-94fc-e36be8bf3e08)

**Comment by 1c3z** [comment]
python3.11 版本太高了， 有兼容性问题。
